In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow import keras
# from tensorflow.keras import layers
# from tensorflow.keras import datasets, layers, models
# from tensorflow.keras.utils import to_categorical
from keras.callbacks import ReduceLROnPlateau
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('iris.csv')
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [3]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4].values

In [4]:
print(X[0:5])
print(y[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa']


In [5]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [6]:
Y = pd.get_dummies(y).values
print(Y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [8]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(20, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
  ])
model

In [9]:
adam_opt = keras.optimizers.Adam(learning_rate=0.005)
model.compile(optimizer=adam_opt,
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [10]:
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2,
                              patience=5, min_lr=0.001)

model.fit(X_train, y_train, batch_size=50, epochs=100, callbacks=[reduce_lr])

Epoch 1/100
3/3 [==============================] - 1s 7ms/step - loss: 1.1272 - accuracy: 0.3083 - lr: 0.0050
Epoch 2/100
3/3 [==============================] - 0s 7ms/step - loss: 1.0878 - accuracy: 0.3083 - lr: 0.0050
Epoch 3/100
3/3 [==============================] - 0s 8ms/step - loss: 1.0649 - accuracy: 0.3083 - lr: 0.0050
Epoch 4/100
3/3 [==============================] - 0s 9ms/step - loss: 1.0399 - accuracy: 0.3083 - lr: 0.0050
Epoch 5/100
3/3 [==============================] - 0s 10ms/step - loss: 1.0105 - accuracy: 0.1417 - lr: 0.0050
Epoch 6/100
3/3 [==============================] - 0s 7ms/step - loss: 0.9574 - accuracy: 0.3750 - lr: 0.0050
Epoch 7/100
3/3 [==============================] - 0s 9ms/step - loss: 0.8810 - accuracy: 0.6333 - lr: 0.0050
Epoch 8/100
3/3 [==============================] - 0s 8ms/step - loss: 0.8417 - accuracy: 0.5083 - lr: 0.0050
Epoch 9/100
3/3 [==============================] - 0s 6ms/step - loss: 0.8230 - accuracy: 0.5583 - lr: 0.0050
Epoch 10/

In [11]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.05036293715238571
Test accuracy: 1.0


In [12]:
y_pred = model.predict(X_test)

1/1 [==============================] - 0s 133ms/step


array([[1.16605705e-12, 3.04135086e-04, 9.99695897e-01],
       [1.22630887e-03, 9.95147288e-01, 3.62638826e-03],
       [9.99961853e-01, 3.81444806e-05, 5.00514190e-08],
       [2.86537627e-10, 3.16085629e-02, 9.68391478e-01],
       [9.99856949e-01, 1.42653065e-04, 3.87411376e-07],
       [6.97694771e-15, 4.59168659e-05, 9.99954104e-01],
       [9.99896765e-01, 1.02879938e-04, 3.25097545e-07],
       [4.57293063e-05, 9.77739036e-01, 2.22152062e-02],
       [4.07170264e-05, 9.79888499e-01, 2.00706869e-02],
       [8.33419443e-04, 9.94954407e-01, 4.21209028e-03],
       [1.18211450e-08, 7.71669000e-02, 9.22833085e-01],
       [7.47926169e-05, 9.76589262e-01, 2.33359560e-02],
       [4.87912803e-05, 9.59943593e-01, 4.00076807e-02],
       [3.15972975e-05, 9.50526655e-01, 4.94417474e-02],
       [1.60908057e-05, 8.75081122e-01, 1.24902807e-01],
       [9.99900818e-01, 9.89727632e-05, 2.30154200e-07],
       [1.88915801e-05, 8.51162374e-01, 1.48818702e-01],
       [4.20766446e-05, 8.73725

In [13]:
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
Predicted: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
